### ISSUE TITLE
运行了forcecop/forcecop容器还需要安装QuickStart里面的东西吗

### ISSUE THREAD

**Issue by vinkdong** [shulieTech/Takin#10]
您好，请问运行了forcecop/forcecop容器还需要安装QuickStart里面的东西吗，感觉需要，又感觉不需要。比较困惑

**Comment by shulieTech** [comment]
不需要哈，直接访问：

**Comment by shulieTech** [comment]
不需要哈，docker容器包含了全部内容，直接访问：
http://47.97.211.203/tro
