### ISSUE TITLE
what's the roadmap

### ISSUE THREAD

**Issue by hermeshephaestus** [shulieTech/Takin#11]
what's the roadmap

**Comment by xhb7636553** [comment]
Document directory？

**Comment by shulieTech** [comment]
近期的规划如下，长期来看，我们会增加新的功能特性。
1. 在agent层兼容更多的中间件或者RPC框架，让接入快速提升；
2. 完善控制台、大数据模块的易用性；
3. 完善接入文档和首次接入的demo。
