### ISSUE TITLE
新增业务活动入口问题

### ISSUE THREAD

**Issue by hanliguohugo** [shulieTech/Takin#111]
1.t_amdb_pradar_link_entrance表中有无数据  无数据
2.surge-deploy任务是否正常启动  启动正常
3.t_trace_all表中是否有最新流量数据 无流量数据
按照文档错误步骤 未能解决问题

**Comment by iengrave** [comment]
探针日志是否有错误信息输出?

**Comment by hanliguohugo** [comment]
> 探针日志是否有错误信息输出?
![1644287175(1)](https://user-images.githubusercontent.com/42508693/152906466-2cb7143f-0bbb-4fd7-8d32-0a4c5a7bb3a1.png) 报了这个

**Comment by iengrave** [comment]
https://docs.shulie.io/docs/opensource/opensource-1d53bj08p42l9
新年好,请参考以上排查手册进行解决。

**Comment by hanliguohugo** [comment]
> https://docs.shulie.io/docs/opensource/opensource-1d53bj08p42l9 新年好,请参考以上排查手册进行解决。
![image](https://user-images.githubusercontent.com/42508693/152923921-1ce3626b-1025-4f1b-b586-ac5fcad3fea0.png)

过年好，麻烦看下 服务启动正常，停止再启动， zk 中还是注册不上。
我这边下载的镜像的surge 包是surge-deploy-pradar-storm-1.0.jar
surge.out 的日志
![image](https://user-images.githubusercontent.com/42508693/152924604-0a3c9d50-7e47-481a-b04d-4eaa3a5745ee.png)

**Comment by iengrave** [comment]
请把zk中的节点内容贴出来,从surge的日志中看是启动正常的

**Comment by hanliguohugo** [comment]
> 请把zk中的节点内容贴出来,从surge的日志中看是启动正常的

![image](https://user-images.githubusercontent.com/42508693/152928253-5ce5f68f-963c-4f56-bc89-48c5d56efe7f.png)

**Comment by iengrave** [comment]
ls /config/log/pradar/server

**Comment by hanliguohugo** [comment]
> ls /config/log/pradar/server
看到了，但是agent 日志还是在报 同样的错误
![image](https://user-images.githubusercontent.com/42508693/152929394-bd830d9b-5f17-4454-b342-6f56e2934e3b.png)
![image](https://user-images.githubusercontent.com/42508693/152929699-3d9531cb-c1a3-4238-a5eb-9d3e7a5d1afc.png)

**Comment by iengrave** [comment]
![image](https://user-images.githubusercontent.com/19290876/153107722-fd382e1e-2649-47b7-a226-4adee458410e.png)
将surge启动命令中的IP映射 左边的容器IP换成172.17.0.4,重新启动surge即可,参考以下:
```
nohup java -Xms256m -Xmx256m -Xss1m -cp surge-deploy-pradar-storm-1.0.jar io.shulie.surge.data.deploy.pradar.bootstrap.PradarTopologyBootStrap -DSourceType=MYSQL -DWorkers=1 -DNet={"你的容器IP":"你的容器宿主机IP"} >surge.out 2>&1 &
```
