### ISSUE TITLE
运行docker命令有报错

### ISSUE THREAD

**Issue by tmaerd** [shulieTech/Takin#12]
按照说明执行一下docker命令有报错：
docker run -d -p 80:80 -p 2181:2181 -p 3306:3306 -p 6379:6379 -p 8086:8086 -p 9000:9000 -p 10032:10032 -p 6628:6628 -p 8000:8000 -p 6627:6627 -p 8888:8888 -p 29900-29999:29900-29999 registry.cn-hangzhou.aliyuncs.com/forcecop/forcecop:v1.0.0

报错部分log：
Archive: /data/apps.zip

replace apps/tro-web/trodb_web_base.sql? [y]es, [n]o, [A]ll, [N]one, [r]ename: NULL

(EOF or read error, treating as "[N]one" ...)

apps_install.sh: line 4: /usr/local/nginx/conf/nginx.conf: No such file or directory

pid not found

apps_install.sh: line 80: nginx: command not found

/usr/bin/tail: inotify cannot be used, reverting to polling: Function not implemented

**Comment by QiaoHao9** [comment]
应该是由于容器没有正常安装 Nginx 所导致的错误，删掉失败的容器，重新执行命令启动容器试下呢？

**Comment by tmaerd** [comment]
> 应该是由于容器没有正常安装 Nginx 所导致的错误。
> 
> ## 方法一
> 删掉失败的容器，重新执行命令启动容器试下呢？
> 
> ## 方法二
> 1. 进入容器内部
> 2. 手动安装 Nginx `yum install -y nginx`
> 3. 执行安装命令 `bash /data/install.sh`

谢谢回复，和我的环境（macos M1）有关系吗，
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by QiaoHao9** [comment]
> > 应该是由于容器没有正常安装 Nginx 所导致的错误。
> > ## 方法一
> > 删掉失败的容器，重新执行命令启动容器试下呢？
> > ## 方法二
> > 
> > 1. 进入容器内部
> > 2. 手动安装 Nginx `yum install -y nginx`
> > 3. 执行安装命令 `bash /data/install.sh`
> 
> 谢谢回复，和我的环境（macos M1）有关系吗，
> WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

目前该镜像还不支持 ARM 平台，后续可能会考虑支持吧。

**Comment by zhang19970916** [comment]
> 按照说明执行一下docker命令有报错：
> docker run -d -p 80:80 -p 2181:2181 -p 3306:3306 -p 6379:6379 -p 8086:8086 -p 9000:9000 -p 10032:10032 -p 6628:6628 -p 8000:8000 -p 6627:6627 -p 8888:8888 -p 29900-29999:29900-29999 registry.cn-hangzhou.aliyuncs.com/forcecop/forcecop:v1.0.0
> 
> 报错部分log：
> Archive: /data/apps.zip
> 
> replace apps/tro-web/trodb_web_base.sql? [y]es, [n]o, [A]ll, [N]one, [r]ename: NULL
> 
> (EOF or read error, treating as "[N]one" ...)
> 
> apps_install.sh: line 4: /usr/local/nginx/conf/nginx.conf: No such file or directory
> 
> pid not found
> 
> apps_install.sh: line 80: nginx: command not found
> 
> /usr/bin/tail: inotify cannot be used, reverting to polling: Function not implemented

现在已经更新了最新的镜像，并且请确保有足够的内存，否则有些应用程序无法正确的启动
