### ISSUE TITLE
通过docker下载提示无法下载

### ISSUE THREAD

**Issue by 15668309109** [shulieTech/Takin#120]
shell提示：
Trying to pull repository registry.cn-hangzhou.aliyuncs.com/shulie-takin/takin ...
Get https://registry.cn-hangzhou.aliyuncs.com/v1/_ping: x509: certificate has expired or is not yet valid

**Comment by zhang19970916** [comment]
docker pull registry.cn-hangzhou.aliyuncs.com/shulie-takin/takin:v1.0.1
这个是可以下载的，我刚测试过
