### ISSUE TITLE
部署初期遇到的问题

### ISSUE THREAD

**Issue by erhua-puppet** [shulieTech/Takin#124]
使用的是快速部署的方法：
参考：https://github.com/shulieTech/Takin/blob/main/README_CN.md

快速接入demo：
参考：https://github.com/shulieTech/EasyDemo/blob/main/docs-cn/READ.md

配置的疑问：
1、demo的env.conf配置
![image](https://user-images.githubusercontent.com/45225770/167100121-7f57380d-fb00-4111-ae33-944757998498.png)

看到示例上面不只加上ip，还加了端口，看demoInstall.sh脚本应该只用IP

2、demo的demoInstall.sh配置
![image](https://user-images.githubusercontent.com/45225770/167100572-c0a45451-f7af-42b8-8ddb-874e52b456bc.png)

怀疑tro-web是老的接口，在takin容器里面也没找到相关的nginx配置，自己改成了takin-web

3、应用接入获取白名单错误
![image](https://user-images.githubusercontent.com/45225770/167101220-4e290fb2-107c-4c27-9458-d5eccd5ee024.png)

easydemo-gateway1.0日志如下：
![image](https://user-images.githubusercontent.com/45225770/167101318-ab32f43f-fd85-4594-b5a7-4341af1efae2.png)

easydemo-usercenter1.0也是一样的报错

现在卡到这了，希望有人帮忙看下

**Comment by zhang19970916** [comment]
更换探针
