### ISSUE TITLE
安装docker一键部署非80端口出现跨域问题

### ISSUE THREAD

**Issue by yisirman** [shulieTech/Takin#126]
![image](https://user-images.githubusercontent.com/15642586/168406259-e6bb5de4-0535-40cd-92ad-2c4c40b0ca47.png)

使用如下命令 我使用的不是80端口 而是其他自定义的端口 但是部署成功后的web api请求出现跨域问题
`docker run -e APPIP=your IP Address -p 80:80 -p 2181:2181 -p 29900-29999:29900-29999 registry.cn-hangzhou.aliyuncs.com/shulie-takin/takin:v1.0.1`

**Comment by yisirman** [comment]
已解决，非80端口需要进入容器路径/data/apps/dist/web/index.html 手动修改serverUrl的地址
建议文档进行同步修改

**Comment by zhangz-2018** [comment]
好的，我们更新一下文档
