### ISSUE TITLE
业务活动列表为空，无法新增业务活动

### ISSUE THREAD

**Issue by test10015** [shulieTech/Takin#127]
业务活动列表为空，无法新增业务活动，已排查以下问题：
1.t_amdb_pradar_link_entrance, t_trace_all表中无数据；
2.surge-deploy任务是正常启动；
3. zookeeper 无节点

**Comment by test10015** [comment]
![image](https://user-images.githubusercontent.com/34162068/168725382-e91abb59-93f1-40ac-9e3e-13217ace5952.png)
![image](https://user-images.githubusercontent.com/34162068/168725398-e7637564-94bd-4868-a43b-570d6f54956d.png)

**Comment by iengrave** [comment]
请检查surge启动脚本,将启动命令中IP映射的172.17.xx.xx IP更换成172.17.0.6,然后重启surge-deploy,并确保zookeeper中的/config/log/pradar/cloud/server节点下有内容注册,然后再次尝试之前的发压流程

**Comment by test10015** [comment]
> 请检查surge启动脚本,将启动命令中IP映射的172.17.xx.xx IP更换成172.17.0.6,然后重启surge-deploy,并确保zookeeper中的/config/log/pradar/cloud/server节点下有内容注册,然后再次尝试之前的发压流程


thx, 改了IP就可以了，请问这是原因什么导致的？

**Comment by iengrave** [comment]
探针访问需要通过宿主机暴露的端口访问,surge是通过启动参数中的容器IP映射到宿主机IP,你的容器IP不是默认的,所以需要修改
