### ISSUE TITLE
探针部署在K8S+docker环境中，demo服务能获取到请求，正常业务服务的接口请求后在takin平台上查询远程调用和业务活动一直不显示请求

### ISSUE THREAD

**Issue by Ro-W** [shulieTech/Takin#133]
已排查以下问题：
1.t_amdb_pradar_link_entrance表中有数据（jdk-http和httpserver的请求有，tomcat的请求没有）；
2.surge-deploy任务是正常启动；
3.t_trace_all表中是有最新流量数据（jdk-http和httpserver的请求有，tomcat的请求没有）；

**Comment by Ro-W** [comment]
所有的探针日志已打包[takin.zip](https://github.com/shulieTech/Takin/files/9401265/takin.zip)
![image](https://user-images.githubusercontent.com/111857681/186123260-65ea4f8c-ce61-48cb-85e0-b5cc66c43702.png)
![image](https://user-images.githubusercontent.com/111857681/186123380-ef07a50d-df9b-4d83-9547-a95f5cac0a94.png)

**Comment by yriiolik** [comment]
确定下应用的探针日志目录一下文件是否存在：
pradar_trace.log.0
pradar_trace.log.idx

这两个是否都存在。 

如果存在，查看 pradar_trace.log.0 文件是否有你说的那几个中间件的trace信息？ tomcat的请求是否有？

如果这个文件也没有， 很可能是 tomcat 不支持， 或者和其他插件冲突了。 你门的业务应用是否有使用skywalking？  如果有，skywalking 必须放在 ttl 的后面， 放在 simulator-agent 的前面，  并且增加参数：  

-Dskywalking.agent.is_cache_enhanced_class=true 
-Dskywalking.agent.class_cache_mode=MEMORY

参考：https://github.com/apache/skywalking/blob/master/docs/en/FAQ/Compatible-with-other-javaagent-bytecode-processing.md
