### ISSUE TITLE
surge服务怎么重启

### ISSUE THREAD

**Issue by fariytale018** [shulieTech/Takin#135]
单独启docker内部的surge服务怎么启？

**Comment by zhang19970916** [comment]
> 

只需要把进程kill掉，然后重新执行启动脚本命令即可(可以通过初始化安装脚本init_install.sh找到: java  -Xms512m -Xmx512m -Xss1m  -cp surge-deploy-pradar-storm-1.0.jar io.shulie.surge.data.deploy.pradar.bootstrap.PradarTopologyBootStrap -DSourceType=MYSQL -DWorkers=1 -DNet={\"172.17.0.2\":\"$APPIP\"} >surge.out 2>&1 &)

参数自定义修改
