### ISSUE TITLE
最新包的使用问题

### ISSUE THREAD

**Issue by duxingxingstar** [shulieTech/Takin#138]
1 agent的日志一直刷这个错误
![image](https://user-images.githubusercontent.com/35559096/225553565-d5954444-2590-4aa1-88ab-c4aa2ab0538d.png)
2 surge正常启动没有错误日志，但是zk上/config/log/pradar/cloud/server该节点一直没有注册上去，导致新增业务入口找不到
https://docs.shulie.io/docs/opensource/opensource-1d9onrs6to163这个问题我没碰到，所以无法参考解决
![image](https://user-images.githubusercontent.com/35559096/225553795-0f0863ad-db44-4fb6-946c-6f58bd045562.png)
3 github上的使用手册跟下载的包差别挺大的，希望按最新的更新下

**Comment by NathanChan** [comment]
邮件已收到！辛苦了，我会在第一时间回复您的！

**Comment by zhang19970916** [comment]
> ![image](https://user-images.githubusercontent.com/35559096/225553565-d5954444-2590-4aa1-88ab-c4aa2ab0538d.png)

这是找不到surge的注册节点，可以查看surege启动命令的脚本替换ip是否跟本机一致，如果不一致替换掉之后重启就行了，启动命令有个参数是{ key: value}结构的
