### ISSUE TITLE
docker安装部分内容补充建议

### ISSUE THREAD

**Issue by chenhengjie123** [shulieTech/Takin#15]
目前 docker 安装部分，`进入容器` 只有一段注释，没有配套的命令，可能部分对 docker 不熟悉的同学会误以为第一条命令就是进入容器。
![image](https://user-images.githubusercontent.com/2800797/123571305-87806080-d7fc-11eb-8de9-40f2e232c8b6.png)

建议：
1、docker run 命令里加上 `--name takin` 参数，指定容器名称
2、下方的文档，加上进入容器命令（如 `docker exec -it takin sh `）

**Comment by shulieTech** [comment]
好的，非常感谢你的建议哈

**Comment by onlonely** [comment]
文档的确太简单...
容器暴露这么多端口干嘛用的?

快速入门要讲一个从没有使用到使用需要做的所有事情,并且解释下为什么要这样做...否则没法"快速开始"

**Comment by shulieTech** [comment]
> 文档的确太简单...
> 容器暴露这么多端口干嘛用的?
> 
> 快速入门要讲一个从没有使用到使用需要做的所有事情,并且解释下为什么要这样做...否则没法"快速开始"

视频教程：https://news.shulie.io/?p=3065
文字版本文档：https://news.shulie.io/?p=2987

目前的文档确实比较简单，后续会逐步完善哈。

**Comment by chzhh393** [comment]
https://docs.shulie.io/docs/opensource/opensource-1d40ib39m90bu
安装部署详细文档已更新~
