### ISSUE TITLE
amdb-receiver-service项目表结构缺失

### ISSUE THREAD

**Issue by hanxiantao** [shulieTech/Takin#16]
amdb-receiver-service项目表依赖MySQL数据库，但未提供表结构，项目中的数据库也无法连接

<img width="414" alt="微信图片_20210630152635" src="https://user-images.githubusercontent.com/45159482/123919661-bbec4c00-d9b7-11eb-93c1-c80008557b7d.png">

**Comment by shulieTech** [comment]
> amdb-receiver-service项目表依赖MySQL数据库，但未提供表结构，项目中的数据库也无法连接
> 
> <img alt="微信图片_20210630152635" width="414" src="https://user-images.githubusercontent.com/45159482/123919661-bbec4c00-d9b7-11eb-93c1-c80008557b7d.png">

数据的账号密码，请查看文档哈。
https://github.com/shulieTech/Takin/blob/main/takin-webapp/doc/QuickStart.md

**Comment by vinzhangya** [comment]
> amdb-receiver-service项目表依赖MySQL数据库，但未提供表结构，项目中的数据库也无法连接
> 
> <img alt="微信图片_20210630152635" width="414" src="https://user-images.githubusercontent.com/45159482/123919661-bbec4c00-d9b7-11eb-93c1-c80008557b7d.png">
 脚本已上传 https://github.com/shulieTech/Takin/blob/main/takin-data/doc/amdb.sql
