### ISSUE TITLE
agent是否支持openjdk？在使用openjdk时因为openjdk的lib目录下并没有tools.jar，因此没有传-Xbootclasspath/a:/$JAVA_HOME/lib/tools.jar这个参数，结果agent启动失败了。

### ISSUE THREAD

**Issue by yanguoqiang** [shulieTech/Takin#23]
![image](https://user-images.githubusercontent.com/41641177/125188929-54ac8280-e268-11eb-827a-dd168ba395b2.png)

**Comment by shulieTech** [comment]
感谢反馈，我反馈给agent的研发同学。
