### ISSUE TITLE
开源版本链路梳理-业务活动新建成功，但是没有"详情"按钮，只有“编辑”和“删除”，没有“详情”按钮怎么查看链路？

### ISSUE THREAD

**Issue by yanguoqiang** [shulieTech/Takin#24]
![image](https://user-images.githubusercontent.com/41641177/125188968-86bde480-e268-11eb-9e45-9e7e01d56761.png)

**Comment by yanguoqiang** [comment]
![image](https://user-images.githubusercontent.com/41641177/125188887-157e3180-e268-11eb-9660-4c70799e1ca3.png)

**Comment by shulieTech** [comment]
这是一个bug，后续优化。
