### ISSUE TITLE
How to build demo quickly?

### ISSUE THREAD

**Issue by xhb7636553** [shulieTech/Takin#4]
I want to build the demo quickly, but I can't download the docker mirror.

**Comment by hengyu-coder** [comment]
This Docker image is public and I can download it locally

**Comment by zhangymPerson** [comment]
you need alter /etc/docker/daemon.json 
like
```json
{
  "registry-mirrors": ["https://q2gr04ke.mirror.aliyuncs.com"]
}
```

**Comment by chukangkang** [comment]
Port 80 cannot be opened on this project 
wearing :403 Forbidden
