### ISSUE TITLE
可以使用 Squash 归一重复提交记录

### ISSUE THREAD

**Issue by QiaoHao9** [shulieTech/Takin#7]
例如重复的提交记录，建议考虑使用 `Squash` 归一。
![image](https://user-images.githubusercontent.com/15377472/123395571-ef536300-d5d2-11eb-8db8-bcbb0e000ed6.png)

**Comment by shulieTech** [comment]
非常感谢你的提醒，那是直接在github页面里手动修改md时引起的。-_-!!!

**Comment by shulieTech** [comment]
同学，你进群了吗？我加下你的微信哈。

**Comment by shulieTech** [comment]
可以加群里的数列-徐汉彬
