### ISSUE TITLE
获取不到服务

### ISSUE THREAD

**Issue by qianmaoliugou** [shulieTech/Takin#84]
按[此方法](https://docs.shulie.io/docs/opensource/opensource-1d9onrs6to163)试了，未解决

操作步骤(大致)
1、按照如下命令运行docker
docker run -e APPIP=10.60.133.56 -p 80:80 -p 2181:2181 -p 29900-29999:29900-29999 -p 3306:3306 -p 6379:6379 registry.cn-hangzhou.aliyuncs.com/shulie-takin/takin:v1.0.1

2、添加demo及探针，然后发起流量请求，数据入库了，但是amdb库未查询到数据

3、看了下发现zookeep地址非宿主机ip，感觉应该是这个原因导致的，如果是，该如何解决？
@xuehuilu @vinzhangya 

![Xnip2021-11-23_18-40-30](https://user-images.githubusercontent.com/5162534/143010006-a31edf23-574c-488b-a962-edb2e3eac42a.jpg)

**Comment by zhang19970916** [comment]
@qianmaoliugou 你好关于这个问题，应该是docker ip的地址与surge-depoy启动脚本中的docker ip地址不一致导致没有替换ip成功，可以将surge-deploy脚本中对应的容器ip地址更改为你实际的容器ip地址即可

**Comment by zhang19970916** [comment]
@qianmaoliugou 脚本在/data/init_install.sh中，脚本为：
nohup java  -Xms512m -Xmx512m -Xss1m  -cp surge-deploy-pradar-storm-1.0.jar io.shulie.surge.data.deploy.pradar.bootstrap.PradarTopologyBootStrap -DSourceType=MYSQL -DWorkers=1 -DNet={\"172.17.0.2\":\"$APPIP\"} >surge.out 2>&1 &
将自己实际的docker ip 替换掉172.17.0.2后执行，启动即可
