### ISSUE TITLE
Must not modify the content in the container.

### ISSUE THREAD

**Issue by QiaoHao9** [shulieTech/Takin#9]
![image](https://user-images.githubusercontent.com/15377472/123401231-288ed180-d5d9-11eb-9dc7-32bcda99aa60.png)

It  confuses me a bit: Why don't we  use `--env`.

We must not modify the content in the container directly!!!

**Comment by shulieTech** [comment]
It is a bad design case in our system, because we never thought about opensource before.-_-!!!

**Comment by QiaoHao9** [comment]
https://github.com/shulieTech/Takin/blob/875790b078accfd6aa67e9e43f3c4917cef0fc63/takin-webapp/tro-web-ui/src/pages/document.ejs#L11

Is it better to set `serverUrl` as `127.0.0.1` or set it with flags when building.
