### ISSUE TITLE
surge启动未找到jar包

### ISSUE THREAD

**Issue by wu-zhishuai** [shulieTech/Takin#98]
surge.out中提示缺少surge-deploy-1.0-jar-with-dependencies.jar
![image](https://user-images.githubusercontent.com/96243354/146389472-65d9c5ea-d886-4215-ad1e-e42a79f5c3be.png)
回到容器data路径下查看发现：只有surge-deploy-pradar-storm-1.0.jar却没有surge-deploy-1.0-jar-with-dependencies.jar
![image](https://user-images.githubusercontent.com/96243354/146393369-a18bf823-ef52-42c0-905e-731ee0a7d18a.png)

当启动命令换成surge-deploy-pradar-storm-1.0.jar时，进行 ps -ef | grep surge，结果如下：
![image](https://user-images.githubusercontent.com/96243354/146393580-26f357f4-5ca9-404c-a224-2d4075e83a95.png)

分别运行两个包 均有报错：
![image](https://user-images.githubusercontent.com/96243354/146396402-e04d01d9-3a80-4571-9f6a-a50b492095bb.png)

请问启动surge到底以哪个jar为准？还是缺少了surge-deploy-1.0-jar-with-dependencies.jar这个包吗？

**Comment by iengrave** [comment]
你的启动命令不正确

**Comment by iengrave** [comment]
nohup java  -Xms256m -Xmx256m -Xss1m  -cp surge-deploy-pradar-storm-1.0.jar io.shulie.surge.data.deploy.pradar.bootstrap.PradarTopologyBootStrap -DSourceType=MYSQL -DWorkers=1 -DNet={\"你的容器IP\":\"你的容器宿主机IP\"} >surge.out 2>&1 &

**Comment by iengrave** [comment]
双引号前面加反斜杠 \

**Comment by wu-zhishuai** [comment]
> 双引号前面加反斜杠 \
第一个问题：容器宿主机IP这块是不是该是应用的IP？
第二个问题：按照您的命令加了反斜杠 \，依旧没有启动



> 双引号前面加反斜杠 \

第一个问题：容器宿主机IP这块是不是该是应用的IP？
第二个问题：按照您的命令加了反斜杠 \，依旧没有启动
![image](https://user-images.githubusercontent.com/96243354/146403282-1749c569-1e6f-4435-923c-7368f07c821f.png)

**Comment by wu-zhishuai** [comment]
> 双引号前面加反斜杠 \
嗯嗯 这样执行就好了 感谢！
nohup java -Xms256m -Xmx256m -Xss1m -cp surge-deploy-pradar-storm-1.0.jar io.shulie.surge.data.deploy.pradar.bootstrap.PradarTopologyBootStrap -DSourceType=MYSQL -DWorkers=1 -DNet={\"你的容器IP\":\"你的容器宿主机IP\"} >surge.out 2>&1 &

**Comment by wu-zhishuai** [comment]
> nohup java -Xms256m -Xmx256m -Xss1m -cp surge-deploy-pradar-storm-1.0.jar io.shulie.surge.data.deploy.pradar.bootstrap.PradarTopologyBootStrap -DSourceType=MYSQL -DWorkers=1 -DNet={"你的容器IP":"你的容器宿主机IP"} >surge.out 2>&1 &
麻烦再次确认下："你的容器宿主机IP"这里是指我takin容器所在主机ip还是应用所在服务器ip？
![image](https://user-images.githubusercontent.com/96243354/146477171-3a5d1d39-5fb6-4ad1-babe-30e6e86c1c3c.png)
